name: "Clamscan"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '44 8 * * 5'
    
jobs:
    build:
  
      name: Scanning repo with clamav
      runs-on: ubuntu-latest
      steps:
        - name: Downloading git repo
          run: |
            git clone --depth=1 --branch=main https://github.com/hexahigh/games.git repo
            rm -rf ./repo/.git
        
        - name: Installing
          run: |
            sudo apt update
            sudo apt install -y clamav
            
        - name: Disabling freshclam service
          run: |
            sudo systemctl stop clamav-freshclam.service
            
        - name: Running freshclam
          run: |
            sudo freshclam
            
        - name: Adding more databases
          run: |
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfo.hdb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfo.ign2' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/javascript.ndb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/spam_marketing.ndb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfohtml.hdb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfoascii.hdb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfoandroid.hdb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfoold.hdb' >> /etc/clamav/freshclam.conf
            sudo sh -c echo 'DatabaseCustomURL https://www.securiteinfo.com/get/signatures/d686bfd922a83b73482ff2e86dd67f6b867610e2c4eecdde75f9cf04fb630d074cf3737b1bad0156f49452e0ea3dc93bb545505bd6875450986d5cefa9a844b1/securiteinfopdf.hdb' >> /etc/clamav/freshclam.conf
      
        - name: Running freshclam
          run: |
            sudo freshclam
            
        - name: Scanning
          run: |
            sudo clamscan -i -r ./repo
